### ISSUE TITLE
creare script de descarcare a datelor

### ISSUE THREAD

**Issue by johnsmithm** [ai-in-actiune/tree-counting-and-classification-in-images#1]
contribuitorii ar trebuie sa poata sa descarce datele ruland un singur script. E util pentru a avea controbuitori noi, pentru a incepe rapid lucru la proiect, pentru a rula proiectul pe un server pentru a se antrena.
- de plasat in src/data/download_data.py (sau scripts/donwload_data.py) 
- sa se salveze in src/data/datasetname

**Comment by johnsmithm** [comment]
- stored in data/raw

**Comment by gorex013** [comment]
Done
