### ISSUE TITLE
plot bboxes from deepforest function

### ISSUE THREAD

**Issue by johnsmithm** [ai-in-actiune/tree-counting-and-classification-in-images#35]
```
def plot_boxes(img, boxes):
  '''code''
  return img_with_boxes
```
https://deepforest.readthedocs.io/en/latest/getting_started.html
https://colab.research.google.com/drive/1gKUiocwfCvcvVfiKzAaf6voiUVL2KK_r?usp=sharing#scrollTo=Q15bw6tFbmO_

**Comment by turcanuandrei** [comment]
assign to me
