### ISSUE TITLE
add dvc to project

### ISSUE THREAD

**Issue by johnsmithm** [ai-in-actiune/tree-counting-and-classification-in-images#40]
- version data: images + annotation to the drive cloud
- version code and experiments
- version models trained

**Comment by johnsmithm** [comment]
## todo: come up with data/models managenet stratedy, a folder for each iteration / rewrite files for each iteration
# data/iterations/iter_0
# data/iterations/iter_0/model_best.pl
# data/iterations/iter_0/predicted_img.csv - used to create corrected
# data/iterations/iter_0/corrected_img.csv - split in train and test
# data/iterations/iter_1

**Comment by turcanuandrei** [comment]
assign to me

**Comment by johnsmithm** [comment]
data https://drive.google.com/file/d/1WRusYYA2BiOIiefW1GZ5rA0pRag-nYQ3/view?usp=sharing
