### ISSUE TITLE
first iteration

### ISSUE THREAD

**Issue by johnsmithm** [ai-in-actiune/tree-counting-and-classification-in-images#46]
- predict unlabeled data
- sort the predicted labels based on confidence (to be done) https://github.com/ai-in-actiune/tree-counting-and-classification-in-images/issues/17
- correct some images

**Comment by johnsmithm** [comment]
data https://drive.google.com/file/d/1WRusYYA2BiOIiefW1GZ5rA0pRag-nYQ3/view?usp=sharing

**Comment by octavflorescu** [comment]
assign to me
