### ISSUE TITLE
Crearea unui model simplu de proba

### ISSUE THREAD

**Issue by johnsmithm** [ai-in-actiune/tree-counting-and-classification-in-images#5]
trebuie sa creem un baseline, dupa care sa imbunatatim

- modelul trebuie sa fie capabil sa ruleze pe un set de date generat cu numpy.rand((batch_size, h,w,channels))
- rulam libraria existenta de detectare a copacilor

**Comment by johnsmithm** [comment]
- deepforest foloseste pytorch retinanet pentru a antrena pe un set de date, o imagine mare este taiata in bucati pentru a antrena modelul, este posibil si clase pt copaci

**Comment by johnsmithm** [comment]
crearea unui notebook pentru a testa modelul deep forest, identifica problemele

**Comment by gorex013** [comment]
instead `img[:, :, ::-1]` might be used the `cv2.cvtColor(img, cv2.COLOR_BGR2RGB)` for more code lisibility
